### ISSUE TITLE
options written to multiple 'options' lines

### ISSUE THREAD

**Issue by doubletwist13** [ahuffman/ansible-resolv#2]
The existing template writes options to multiple lines. I'm not sure if this will work in different OSes. I think it's a fairly simple change to write the options to a single line, which will likely be compatible with more different OSes, using a join instead of a for loop.

# {{ ansible_managed }}

{% if resolv_search %}
search {{ resolv_search|join(' ') }}
{% endif %}
{% if resolv_domain %}
domain {{ resolv_domain }}
{% endif %}
{% for i in resolv_nameservers %}
nameserver {{ i }}
{% endfor %}
{% for i in resolv_sortlist %}
sortlist {{ i }}
{% endfor %}
{% if resolv_options %}
options {{ resolv_options|join(' ') }}
{% endif %}

**Comment by ahuffman** [comment]
I'd be happy to take a pull request if you have time to make the commit.  Thanks.

**Comment by ahuffman** [comment]
This has been fixed.
